bayesianAttributesInterpretation <- function(jaspResults, dataset, options, state=NULL){

  if(is.null(state))
      state 							    <- list()

  options$plotPriorAndPosteriorAdditionalInfo <- TRUE
  options$show <- "percentage"
  options$statistic <- "bound"

  jaspResults$title 					<- "Audit Report"

  jaspResults[["introParagraph"]] <- createJaspHtml("This report is automatically generated by JASP and serves the purpose of providing a statistically correct interpretation
                                                      for the planning and evaluation of a <u>Bayesian</u> attributes bound. This report is generated through summary statistics and
                                                      is <u><b>not</b></u> admissable in an audit. For an admissable report on your data, visit the <i>evaluation</i> section.", "p")
  jaspResults[["introParagraph"]]$position <- 1

  jaspResults[["objective"]] <- createJaspHtml("<u>Procedure</u>", "h2")
  jaspResults[["objective"]]$position <- 2

  jaspResults[["objectiveParagraph"]] <- createJaspHtml(paste0("The objective of an attributes bound procedure is to determine with a specified <b>", options$confidence*100,"%</b> confidence whether the percentage
                                                                of errors in the target population is lower than the specified materiality of <b>",options$materiality*100,"%</b>. An attributes bound procedure considers
                                                                the observations in the population to be of one of two categories: 1) the observation is fully incorrect or 2) the observation
                                                                is fully correct."), "p")
  jaspResults[["objectiveParagraph"]]$position <- 3

  jaspResults[["priorKnowledge"]] <- createJaspHtml("<u>Prior knowledge</u>", "h2")
  jaspResults[["priorKnowledge"]]$position <- 4

  .bayesianAttributesPlanning(options, jaspResults)
  result                      <- jaspResults[["result"]]$object

  if(options[["expected.errors"]] == "kPercentage"){
    expected.errors <- paste0(round(options[["kPercentageNumber"]] * 100, 2), "%")
    max.errors <- ceiling(options[["kPercentageNumber"]] * result[["n"]])
  } else {
    expected.errors <- options[["kNumberNumber"]]
    max.errors <- options[["kNumberNumber"]] + 1
  }

  jaspResults[["priorKnowledgeParagraph"]] <- createJaspHtml(paste0("Prior to the substantive testing phase, the inherent risk was determined to be <b>",options$IR,"</b>. The internal control risk was determined
                                                                      to be <b>", options$CR,"</b>. According to the Audit Risk Model, the required detection risk to then maintain an audit risk of <b>", (1 - options$confidence) * 100, "%</b> should be <b>",round(result[["alpha"]]*100, 2), "%</b>.
                                                                      As prior knowledge, the most likely error in the data was specified to be <b>", expected.errors ,"</b>. The probability distribution that corresponds with
                                                                      this prior knowledge is the <b>Beta(",round(result[["priorA"]],2), ",", round(result[["priorB"]],2),")</b> distribution. This probability distribution states that there is a <b>",
                                                                      round(pbeta(options[["materiality"]], result[["priorA"]],result[["priorB"]])*100, 2) ,"%</b> prior probability that the
                                                                      population error is lower than materiality. The sample size that is required to prove an <b>",options$materiality*100,"%</b> upper confidence bound, assuming
                                                                      the sample contains <b>", expected.errors ,"</b> full errors, is <b>", result[["n"]] ,"</b>. Consequently, if <b>", max.errors ,"</b> or more full errors are found, the population cannot be approved."), "p")
  jaspResults[["priorKnowledgeParagraph"]]$position <- 5

  if(options[["plotPrior"]]){
    if(is.null(jaspResults[["priorPlot"]]))
    {
    jaspResults[["priorPlot"]] 		<- .plotPriorBayesianAttributesPlanning(options, result, jaspResults, plotWidth = 600, plotHeight = 300)
    jaspResults[["priorPlot"]]		  $dependOnOptions(c("IR", "CR", "confidence", "materiality", "expected.errors", "limx", "plotPriorAndPosterior",
                                                      "plotPriorAndPosteriorAdditionalInfo", "show", "statistic",
                                                      "kPercentageNumber", "kNumberNumber"))
    jaspResults[["priorPlot"]]$position <- 6
    }
  }

  if(options[["n"]] != 0){

    jaspResults[["resultTitle"]] <- createJaspHtml("<u>Result</u>", "h2")
    jaspResults[["resultTitle"]]$position <- 7

    .summaryBayesianAttributesBound(options, jaspResults)
    result                      <- jaspResults[["result"]]$object

    jaspResults[["resultParagraph"]] <- createJaspHtml(paste0("The sample consisted of <b>",options$n, "</b> observations, <b>",options$k, "</b> of which were found to contain a full error. The knowledge from these data, com-
                                                                bined with the prior knowledge results in an <b>",options$confidence*100, "%</b> upper confidence bound of <b>",round(result[["bound"]]*100, 2),"%</b>. The cumulative knowledge states that there
                                                                is a <b>",options$confidence*100, "%</b> probability that the true error proportion in the population is lower than <b>",round(result[["bound"]]*100, 2),"%</b>."), "p")
    jaspResults[["resultParagraph"]]$position <- 8

    if(options[["plotPriorAndPosterior"]]){
      if(is.null(jaspResults[["priorAndPosteriorPlot"]]))
      {
        jaspResults[["priorAndPosteriorPlot"]] 		<- .plotPriorAndPosteriorBayesianAttributesBound(options, result, jaspResults, plotWidth = 600, plotHeight = 300)
        jaspResults[["priorAndPosteriorPlot"]]		$dependOnOptions(c("IR", "CR", "confidence", "n", "k", "limx", "statistic",
                                                                    "plotPriorAndPosterior", "plotPriorAndPosteriorAdditionalInfo",
                                                                    "materiality", "show", "expected.errors", "kPercentageNumber", "kNumberNumber"))
        jaspResults[["priorAndPosteriorPlot"]]$position <- 9
      }
    }

    jaspResults[["conclusionTitle"]] <- createJaspHtml("<u>Conclusion</u>", "h2")
    jaspResults[["conclusionTitle"]]$position <- 10

    if(result[["bound"]] < options[["materiality"]]){
      above_below <- "lower"
      approve <- "<b>no material misstatement</b>"
    } else {
      above_below <- "higher"
      approve <- "<b>material misstatement, or more information has to be seen.</b>"
    }

    jaspResults[["conclusionParagraph"]] <- createJaspHtml(paste0("To approve these data, a <b>", options$confidence*100 ,"%</b> upper confidence bound on the population proportion of full errors should be determined to be
                                                                    lower than materiality, in this case <b>", options$materiality*100 ,"%</b>. For the current data, the confidence bound is ", above_below ," than materiality. The conclusion for
                                                                    these data is that the data contain ", approve ,"."), "p")
    jaspResults[["conclusionParagraph"]]$position <- 11

  }

  # Save the state
  state[["options"]] 					<- options
  return(state)

}
